import { brandColors, commonTypography } from "./tokens";
import type { ThemeDefinition } from "./types";

export const bitInnovation = {
  id: "bit-innovation",
  name: "北理·科创",
  englishName: "BIT Innovation",
  description:
    "面向科研、工程、学术探索、拔尖培养、创新成果与科研成长的理性主题。",
  keywords: [
    "科研",
    "科技",
    "工程",
    "创新",
    "成果",
    "实验室",
    "AI",
    "项目",
    "学科体验",
    "研学",
    "拔尖培养",
  ],
  recommendedFor: [
    "科研成果与人物",
    "工程项目与实验室",
    "学科专业体验",
    "国际研学与创新实践",
    "拔尖人才培养",
  ],
  avoidFor: ["纯生活化校园内容", "节日祝福", "纯行政通知", "普通会议新闻"],
  tokens: {
    colors: {
      background: brandColors.bitWhite,
      surface: "#F4F8F6",
      surfaceMuted: "#F7FAF8",
      surfaceStrong: "#ECF4EF",
      primary: brandColors.bitGreen,
      primaryStrong: brandColors.bitDarkGreen,
      accent: "#557567",
      textStrong: "#16231C",
      text: "#2B3530",
      textSecondary: "#657069",
      textMuted: "#839087",
      border: "#D6E3DA",
      borderStrong: "#B9CFC0",
      codeBackground: "#EFF5F1",
      tableHeader: "#E3EFE7",
    },
    typography: {
      ...commonTypography,
      bodyLineHeight: "1.86",
      titleSize: "30px",
      titleLineHeight: "1.32",
    },
    spacing: {
      pageInline: "18px",
      sectionGap: "34px",
      paragraphGap: "15px",
      cardPadding: "17px",
    },
    radius: { small: "3px", medium: "6px", large: "8px", image: "6px" },
    border: { width: "1px", style: "solid" },
    shadow: { card: "none" },
  },
  componentDefaults: {
    "article-title": { density: "compact", emphasis: "structured", shape: "technical" },
    "section-title": { density: "compact", emphasis: "structured", shape: "technical" },
    "quote-card": { density: "compact", emphasis: "structured", shape: "technical" },
    "info-card": { density: "compact", emphasis: "structured", shape: "technical" },
    image: { density: "compact", emphasis: "structured", shape: "technical" },
  },
  themeVariants: [
    { id: "research", name: "科研", description: "默认科研长文与成果解读。" },
    { id: "data", name: "数据", description: "加强指标、编号和信息摘要。" },
    { id: "profile", name: "人物", description: "增加人物图片、引语和留白。" },
    { id: "project", name: "项目", description: "突出项目参数、步骤和信息卡。" },
    { id: "explore", name: "探索", description: "突出研学、体验与阶段式叙事。" },
  ],
  defaultVariant: "research",
} satisfies ThemeDefinition;
