import {
  ArticleTitle,
  BodyText,
  BulletList,
  ChapterTitle,
  CodeBlock,
  Divider,
  Ending,
  Highlight,
  Image,
  ImageCaption,
  InfoCard,
  LeadText,
  Note,
  NumberList,
  QuoteCard,
  SectionTitle,
  StepList,
  Subtitle,
  Table,
} from "./articleComponents";
import type { ComponentRegistryEntry } from "./types";

const defaultVariant = ["default"] as const;

export const componentRegistry = [
  {
    id: "article-title",
    displayName: "ArticleTitle",
    description: "文章主标题与可选上眉标签。",
    supportedComponentVariants: [...defaultVariant],
    component: ArticleTitle,
  },
  {
    id: "subtitle",
    displayName: "Subtitle",
    description: "主标题下的辅助标题。",
    supportedComponentVariants: [...defaultVariant],
    component: Subtitle,
  },
  {
    id: "section-title",
    displayName: "SectionTitle",
    description: "文章普通章节标题。",
    supportedComponentVariants: [...defaultVariant],
    component: SectionTitle,
  },
  {
    id: "chapter-title",
    displayName: "ChapterTitle",
    description: "文章叙事中的篇章或阶段标题。",
    supportedComponentVariants: [...defaultVariant],
    component: ChapterTitle,
  },
  {
    id: "body-text",
    displayName: "BodyText",
    description: "适合连续阅读的正文段落。",
    supportedComponentVariants: [...defaultVariant],
    component: BodyText,
  },
  {
    id: "lead-text",
    displayName: "LeadText",
    description: "文章开场导语或摘要。",
    supportedComponentVariants: [...defaultVariant],
    component: LeadText,
  },
  {
    id: "highlight",
    displayName: "Highlight",
    description: "关键结论或数字成果强调。",
    supportedComponentVariants: ["default", "metric"],
    component: Highlight,
  },
  {
    id: "quote-card",
    displayName: "QuoteCard",
    description: "人物原话、专家观点或正式引用。",
    supportedComponentVariants: [...defaultVariant],
    component: QuoteCard,
  },
  {
    id: "info-card",
    displayName: "InfoCard",
    description: "时间、地点、参数与关键信息。",
    supportedComponentVariants: [...defaultVariant],
    component: InfoCard,
  },
  {
    id: "note",
    displayName: "Note",
    description: "轻量注释、来源或补充说明。",
    supportedComponentVariants: [...defaultVariant],
    component: Note,
  },
  {
    id: "bullet-list",
    displayName: "BulletList",
    description: "无序信息列表。",
    supportedComponentVariants: [...defaultVariant],
    component: BulletList,
  },
  {
    id: "number-list",
    displayName: "NumberList",
    description: "带稳定编号的信息列表。",
    supportedComponentVariants: [...defaultVariant],
    component: NumberList,
  },
  {
    id: "step-list",
    displayName: "StepList",
    description: "流程、方法或活动步骤。",
    supportedComponentVariants: [...defaultVariant],
    component: StepList,
  },
  {
    id: "image",
    displayName: "Image",
    description: "带替代文本的文章图片。",
    supportedComponentVariants: [...defaultVariant],
    component: Image,
  },
  {
    id: "image-caption",
    displayName: "ImageCaption",
    description: "由内容数据提供的图片说明。",
    supportedComponentVariants: [...defaultVariant],
    component: ImageCaption,
  },
  {
    id: "divider",
    displayName: "Divider",
    description: "轻量文章节奏分隔。",
    supportedComponentVariants: [...defaultVariant],
    component: Divider,
  },
  {
    id: "ending",
    displayName: "Ending",
    description: "不自动添加 CTA 的文章结束语。",
    supportedComponentVariants: [...defaultVariant],
    component: Ending,
  },
  {
    id: "code-block",
    displayName: "CodeBlock",
    description: "代码、命令与配置文本的稳定展示。",
    supportedComponentVariants: [...defaultVariant],
    component: CodeBlock,
  },
  {
    id: "table",
    displayName: "Table",
    description: "普通二维表格与可选标题。",
    supportedComponentVariants: [...defaultVariant],
    component: Table,
  },
] satisfies ComponentRegistryEntry[];
