import type { CompositionRegistryEntry } from "./types";

export const compositionRegistry = [
  {
    id: "hero-visual",
    description: "文章标题、可选开场段与一张主视觉组成的首屏。",
    sourceTypes: ["paragraph", "image", "image-caption"],
    minimumImages: 1,
    maximumImages: 1,
    allowsArticleTitle: true,
  },
  {
    id: "section-opener",
    description: "章节标题与可选导语组成的轻量开篇。",
    sourceTypes: ["heading", "paragraph"],
    minimumImages: 0,
    maximumImages: 0,
    allowsArticleTitle: false,
  },
  {
    id: "photo-pair",
    description: "两张关联图片、各自图注与可选叙事段落。",
    sourceTypes: ["heading", "paragraph", "quote", "image", "image-caption", "table"],
    minimumImages: 2,
    maximumImages: 2,
    allowsArticleTitle: false,
  },
  {
    id: "photo-grid",
    description: "三至四张关联图片、图注与可选叙事段落。",
    sourceTypes: ["heading", "paragraph", "quote", "image", "image-caption", "table"],
    minimumImages: 3,
    maximumImages: 4,
    allowsArticleTitle: false,
  },
  {
    id: "media-story",
    description: "可选章节标题、正文、引用与一至两张叙事图片。",
    sourceTypes: ["heading", "paragraph", "quote", "image", "image-caption", "table"],
    minimumImages: 1,
    maximumImages: 2,
    allowsArticleTitle: false,
  },
  {
    id: "profile-spotlight",
    description: "人物标题、肖像、人物文字或原话组成的聚焦段。",
    sourceTypes: ["heading", "paragraph", "quote", "image", "image-caption"],
    minimumImages: 1,
    maximumImages: 1,
    allowsArticleTitle: false,
  },
  {
    id: "achievement-spotlight",
    description: "成果标题、可选图片、正文、引用或指标表组成的成果段。",
    sourceTypes: ["heading", "paragraph", "quote", "image", "image-caption", "table"],
    minimumImages: 0,
    maximumImages: 1,
    allowsArticleTitle: false,
  },
  {
    id: "full-width-story",
    description: "一至三张横向图片以通栏节奏连接标题、正文和图注。",
    sourceTypes: ["heading", "paragraph", "quote", "image", "image-caption", "table"],
    minimumImages: 1,
    maximumImages: 3,
    allowsArticleTitle: false,
  },
  {
    id: "asymmetric-photo-pair",
    description: "两张同场景图片以主次明确的非对称比例组合。",
    sourceTypes: ["heading", "paragraph", "quote", "image", "image-caption", "table"],
    minimumImages: 2,
    maximumImages: 2,
    allowsArticleTitle: false,
  },
  {
    id: "portrait-story",
    description: "人物肖像与叙事文字组成的纵向人物故事。",
    sourceTypes: ["heading", "paragraph", "quote", "image", "image-caption", "table"],
    minimumImages: 1,
    maximumImages: 1,
    allowsArticleTitle: false,
  },
  {
    id: "quote-with-portrait",
    description: "人物肖像、原话和必要背景信息组成的引语节点。",
    sourceTypes: ["heading", "paragraph", "quote", "image", "image-caption"],
    minimumImages: 1,
    maximumImages: 1,
    allowsArticleTitle: false,
  },
  {
    id: "poster-feature",
    description: "海报或竖版视觉作为段落主角，文字保持克制。",
    sourceTypes: ["heading", "paragraph", "quote", "image", "image-caption"],
    minimumImages: 1,
    maximumImages: 1,
    allowsArticleTitle: false,
  },
  {
    id: "visual-climax",
    description: "一至四张关键画面构成文章视觉高潮。",
    sourceTypes: ["heading", "paragraph", "quote", "image", "image-caption", "table"],
    minimumImages: 1,
    maximumImages: 4,
    allowsArticleTitle: false,
  },
  {
    id: "closing-visual",
    description: "收束段与可选结尾图片、图注组成的结尾。",
    sourceTypes: ["paragraph", "quote", "image", "image-caption"],
    minimumImages: 0,
    maximumImages: 1,
    allowsArticleTitle: false,
  },
] as const satisfies readonly CompositionRegistryEntry[];

export const compositionRegistryById = Object.fromEntries(
  compositionRegistry.map((entry) => [entry.id, entry]),
) as Record<(typeof compositionRegistry)[number]["id"], (typeof compositionRegistry)[number]>;
